---


- name: deploy scripts
  template:
    src: "scripts/{{ item }}"
    dest: "{{ easy_rsa_scripts_dir }}/{{ item }}"
    owner: "{{ easy_rsa_admin_user }}"
    group: "{{ easy_rsa_group }}"
    mode: "0755"
  loop:
    - easyrsa-ca
    - easyrsa-request
    - ca_req_sign.sh
    - ca_import_sign.sh
    - req_and_import_sign.sh
    - revoke_expired.sh
  register: t_easy_rsa_scripts_update
