---

- include_tasks: generate_certificate.yml
  vars:
    cn: "{{ item.cn }}"
    dns: "{{ item.dns | d([]) }}"
    type: "{{ item.type | d('serverClient') }}"
  loop: "{{ easy_rsa_default_certificates_to_generate + easy_rsa_custom_certificates_to_generate }}"
