---

- name: "check version {{ easy_rsa_version }}"
  stat:
    path: "{{ easy_rsa_dist_bin }}"
  register: t_easy_rsa_dist_bin_stat


- block:
    - name: "download easy-rsa {{ easy_rsa_version }}"
      get_url:
        url: "{{ easy_rsa_release_archive_url }}"
        dest: "{{ easy_rsa_distfiles_dir }}/{{ easy_rsa_release_archive }}"
        mode: "0444"

    - name: "extract archive {{ easy_rsa_version }}"
      unarchive:
        remote_src: yes
        src: "{{ easy_rsa_distfiles_dir }}/{{ easy_rsa_release_archive }}"
        dest: "{{ easy_rsa_dir }}"
        owner: "{{ easy_rsa_admin_user }}"
        group: "{{ easy_rsa_group }}"
        mode: "go-w"

  when: not t_easy_rsa_dist_bin_stat.stat.exists


- name: "link {{ easy_rsa_version }}"
  file:
    src: "{{ easy_rsa_dir }}/{{ easy_rsa_release_dist }}"
    dest: "{{ easy_rsa_dist_dir }}"
    owner: "{{ easy_rsa_admin_user }}"
    group: "{{ easy_rsa_group }}"
    force: yes
    state: link
