---

- block:
    - include_tasks: context.yml

    - include_tasks: _accounts.yml
      vars:
        _accounts_groups: "{{ easy_rsa_groups }}"
        _accounts_users: "{{ easy_rsa_users }}"

    - include_tasks: workspace.yml
      vars:
        workspace_fs: "{{ easy_rsa_dir }}"
        workspace_directories: "{{ easy_rsa_directories }}"

    - include_tasks: install.yml

    - block:

        - include_tasks: configure.yml
          vars:
            easy_rsa_instance_type: ca
            easy_rsa_instance_dir: "{{ easy_rsa_ca_dir }}"
            easy_rsa_instance_vars: "{{ easy_rsa_vars_base + easy_rsa_vars_dn + easy_rsa_vars_security + easy_rsa_vars_ca }}"

        - include_tasks: generate_certificate.yml
          vars:
            cn: "{{ item.cn }}"
            dns: "{{ item.dns | d([]) }}"
            type: "{{ item.type | d('serverClient') }}"
          loop: "{{ easy_rsa_default_ca_certificates_to_generate + easy_rsa_custom_ca_certificates_to_generate }}"

      when: easy_rsa_want_ca

    - block:

        - include_tasks: configure.yml
          vars:
            easy_rsa_instance_type: request
            easy_rsa_instance_dir: "{{ easy_rsa_request_dir }}"
            easy_rsa_instance_vars: "{{ easy_rsa_vars_base + easy_rsa_vars_dn + easy_rsa_vars_security + easy_rsa_vars_request }}"

        - include_tasks: generate_request.yml
          vars:
            cn: "{{ item.cn }}"
            dns: "{{ item.dns | d([]) }}"
            type: "{{ item.type | d('serverClient') }}"
          loop: "{{ easy_rsa_default_requests_to_generate + easy_rsa_custom_requests_to_generate }}"

      when: easy_rsa_want_request

    - include_tasks: deploy_scripts.yml

    - include_tasks: deploy_maintenance_tasks.yml
      when: easy_rsa_want_ca

  when: want_easy_rsa

- name: "set has_easy_rsa to {{ want_easy_rsa }}"
  set_fact:
    has_easy_rsa: "{{ want_easy_rsa }}"
