---

- block:
    - include_tasks: context.yml

    - include_tasks: accounts.yml
      vars:
        accounts_groups: "{{ easy_rsa_groups }}"
        accounts_users: "{{ easy_rsa_users }}"

    - include_tasks: workspace.yml
      vars:
        workspace_fs: "{{ easy_rsa_dir }}"
        workspace_directories: "{{ easy_rsa_directories }}"

    - include_tasks: install.yml

    - include_tasks: configure.yml
      vars:
        easy_rsa_instance_type: ca
        easy_rsa_instance_dir: "{{ easy_rsa_ca_dir }}"
        easy_rsa_instance_vars: "{{ easy_rsa_vars_base + easy_rsa_vars_dn + easy_rsa_vars_security + easy_rsa_vars_ca }}"

    - include_tasks: configure.yml
      vars:
        easy_rsa_instance_type: request
        easy_rsa_instance_dir: "{{ easy_rsa_request_dir }}"
        easy_rsa_instance_vars: "{{ easy_rsa_vars_base + easy_rsa_vars_dn + easy_rsa_vars_security + easy_rsa_vars_request }}"

    - include_tasks: generate_certificates.yml

    - include_tasks: deploy_scripts.yml

    - include_tasks: deploy_maintenance_tasks.yml

  when: want_easy_rsa

- name: "set has_easy_rsa to {{ want_easy_rsa }}"
  set_fact:
    has_easy_rsa: "{{ want_easy_rsa }}"
