---

- block:
    - include: context.yml

    - include: workspace.yml

    - include: install.yml

    - include: setup.yml

  when: want_easy_rsa

- name: "set has_easy_rsa to {{ want_easy_rsa }}"
  set_fact:
    has_easy_rsa: "{{ want_easy_rsa }}"
