---

- name: check pki init state
  stat:
    path: "{{ easy_rsa_pki_dir }}/pki"
  register: t_easyrsa_pki

- name: init pki
  command: /usr/local/bin/easyrsa init-pki
  args:
    chdir: "{{ easy_rsa_pki_dir }}"
  become: yes
  become_user: "{{ easy_rsa_user }}"
  when: not t_easyrsa_pki.stat.exists

- name: check requests state
  stat:
    path: "{{ easy_rsa_requests_dir }}/pki"
  register: t_easyrsa_requests

- name: init pki
  command: /usr/local/bin/easyrsa init-pki
  args:
    chdir: "{{ easy_rsa_requests_dir }}"
  become: yes
  become_user: "{{ easy_rsa_user }}"
  when: not t_easyrsa_requests.stat.exists
